### ISSUE TITLE
Add Funfunfunction

### ISSUE THREAD

**Issue by agarrharr** [epoyraz/Awesome-Youtube-Channels#3]
I'm not sure what category it would go under, but you should add [Funfunfunction](https://www.youtube.com/channel/UCO1cgjhGzsSYb1rsB4bFe4Q).

**Comment by epoyraz** [comment]
He describes himself as a Front-End-Dev and most of his Video/Vlogs relate to Javascript.
I'll add him to Web-Development. 
Thanks ! :+1:
